"""
NEXUS Framework - Command Line Interface

Provides nexus init and nexus run commands for easy project setup.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

app = typer.Typer(
    name="nexus",
    help="NEXUS Framework - Unified Agentic Framework",
    add_completion=False,
)
console = Console()


@app.command()
def init(
    path: Path = typer.Argument(".", help="Project directory path"),
    name: str = typer.Option("nexus-agent", "--name", "-n", help="Agent name"),
    provider: str = typer.Option("ollama", "--provider", "-p", help="LLM provider"),
    model: str = typer.Option("llama3.2", "--model", "-m", help="Model name"),
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing"),
):
    """Initialize a new NEXUS project."""
    path = path.expanduser().resolve()
    if path.exists() and not force:
        if any(path.iterdir()):
            console.print("[red]Directory not empty. Use --force to overwrite.[/red]")
            raise typer.Exit(1)
    path.mkdir(parents=True, exist_ok=True)
    config_content = f"""
# NEXUS Configuration
# Generated by nexus init

llm:
  provider: {provider}
  model: {model}
  temperature: 0.7

memory:
  provider: sqlite
  path: ./nexus.db

security:
  sandbox_enabled: true
  audit_logging: true

agent_name: {name}
log_level: INFO
"""
    config_path = path / "nexus.yaml"
    config_path.write_text(config_content)
    (path / "skills").mkdir(exist_ok=True)
    (path / "memory").mkdir(exist_ok=True)
    console.print(Panel.fit(
        "[green]Done![/green] NEXUS project initialized\n\n"
        f"Project: {path}\n"
        f"Provider: {provider}\n"
        f"Model: {model}\n\n"
        "[cyan]Next steps:[/cyan]\n"
        f"  cd {path}\n"
        "  nexus run"
    ))


@app.command()
def run(
    config: Optional[Path] = typer.Option(None, "--config", "-c", help="Config file"),
    prompt: Optional[str] = typer.Option(None, "--prompt", "-p", help="Initial prompt"),
    interactive: bool = typer.Option(True, "--interactive/-i", "--batch/-b", help="Interactive"),
):
    """Run the NEXUS agent."""
    from nexus.config import load_config, create_adapter_from_config
    try:
        cfg = load_config(config)
        console.print(f"[cyan]Provider:[/cyan] {cfg.llm.provider}")
        console.print(f"[cyan]Model:[/cyan] {cfg.llm.model}")
        llm = create_adapter_from_config(cfg)
        console.print("[green]OK[/green] Adapter created")
        model_info = asyncio.run(llm.get_model_info())
        table = Table(title="Model Information")
        table.add_column("Property", style="cyan")
        table.add_column("Value", style="green")
        table.add_row("Model", model_info.id)
        table.add_row("Context Window", str(model_info.context_window))
        table.add_row("Supports Vision", str(model_info.supports_vision))
        table.add_row("Supports Tools", str(model_info.supports_tools))
        console.print(table)
    except FileNotFoundError:
        console.print("[red]No config. Run nexus init first.[/red]")
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"[red]Error: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def doctor(
    config: Optional[Path] = typer.Option(None, "--config", "-c", help="Config file"),
):
    """Run diagnostics on NEXUS configuration."""
    from nexus.config import load_config, create_adapter_from_config
    console.print(Panel.fit("[cyan]NEXUS Doctor[/cyan]"))
    issues = []
    try:
        cfg = load_config(config)
        console.print("[green]OK[/green] Configuration loaded")
        console.print(f"  Provider: {cfg.llm.provider}")
        console.print(f"  Model: {cfg.llm.model}")
    except FileNotFoundError:
        issues.append("Configuration file not found")
        console.print("[red]X[/red] Configuration not found")
    try:
        llm = create_adapter_from_config(cfg)
        console.print("[green]OK[/green] LLM adapter created")
    except Exception as e:
        issues.append(f"Adapter creation failed: {e}")
        console.print(f"[red]X[/red] Adapter failed: {e}")
    if issues:
        console.print(f"\n[red]Found {len(issues)} issue(s)[/red]")
        raise typer.Exit(1)
    else:
        console.print("\n[green]All checks passed![/green]")


@app.command()
def version():
    """Show NEXUS version."""
    from nexus import __version__
    console.print(f"NEXUS Framework v{__version__}")


if __name__ == "__main__":
    app()
